# Generated by Django 5.1.6 on 2025-02-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("title", "content")},
        ),
    ]
