# Generated by Django 5.1.6 on 2025-02-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_title_alter_article_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="article",
            unique_together=set(),
        ),
    ]
